### ISSUE TITLE
同学 你的数据集是不是少了 

### ISSUE THREAD

**Issue by lidream** [liAoI/rumorDetection#1]
ma的数据集有4665条 你的怎么只有2789？

**Comment by liAoI** [comment]
嗯，这2789条是从4665里面去重得到的。通过简单的去重处理，发现很多文本非常相似，所以进行了去重，原数据集可以到百度云链接：https://pan.baidu.com/s/1r9A_AouK8D51wE9lgCaVLw 
提取码：9fmi 
这里下载。
